// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE

import * as Jest from "../node_modules/@glennsl/bs-jest/src/jest.js";
import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";

Jest.describe("Expect", (function (param) {
        return Jest.test("toBe", (function (param) {
                      return Jest.Expect[/* toBe */2](3, Jest.Expect[/* expect */0](3));
                    }));
      }));

Jest.describe("Expect.Operators", (function (param) {
        return Jest.test("==", (function (param) {
                      return Curry._2(Jest.Expect[/* Operators */25][/* == */0], Jest.Expect[/* expect */0](3), 3);
                    }));
      }));

export {
  
}
/*  Not a pure module */
