// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var JSON$ReasonSuperTinyCompiler = require("../src/JSON.bs.js");
var Combinators$ReasonSuperTinyCompiler = require("../src/Combinators.bs.js");

Jest.describe("JSON parser", (function (param) {
        Jest.test("surround", (function (param) {
                var surround = function (openP, bodyP, closeP) {
                  return Curry._2(Combinators$ReasonSuperTinyCompiler.$great$great$eq, openP, (function (param) {
                                return Curry._2(Combinators$ReasonSuperTinyCompiler.$great$great$eq, JSON$ReasonSuperTinyCompiler.Parser[/* whitespace */0], (function (param) {
                                              return Curry._2(Combinators$ReasonSuperTinyCompiler.$great$great$eq, bodyP, (function (result) {
                                                            return Curry._2(Combinators$ReasonSuperTinyCompiler.$great$great$eq, JSON$ReasonSuperTinyCompiler.Parser[/* whitespace */0], (function (param) {
                                                                          return Curry._2(Combinators$ReasonSuperTinyCompiler.$less$$great, closeP, (function (param) {
                                                                                        return result;
                                                                                      }));
                                                                        }));
                                                          }));
                                            }));
                              }));
                };
                var result = Combinators$ReasonSuperTinyCompiler.run(surround(Combinators$ReasonSuperTinyCompiler.string("["), Combinators$ReasonSuperTinyCompiler.string("a"), Combinators$ReasonSuperTinyCompiler.string("]")), "[     a  ]");
                return Curry._2(Jest.Expect[/* Operators */25][/* = */5], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), "a");
              }));
        Jest.test("null", (function (param) {
                var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* null */2], "null");
                return Curry._2(Jest.Expect[/* Operators */25][/* == */0], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JNull */1);
              }));
        Jest.test("undefined", (function (param) {
                var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* undefined */1], "undefined");
                return Curry._2(Jest.Expect[/* Operators */25][/* == */0], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JUndefined */0);
              }));
        Jest.test("string", (function (param) {
                var result = Combinators$ReasonSuperTinyCompiler.run(Curry._2(Combinators$ReasonSuperTinyCompiler.$great$great$eq, JSON$ReasonSuperTinyCompiler.Parser[/* whitespace */0], (function (param) {
                            return JSON$ReasonSuperTinyCompiler.Parser[/* quotedString */7];
                          })), " \"what\"");
                return Curry._2(Jest.Expect[/* Operators */25][/* = */5], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JString */Block.__(1, ["what"]));
              }));
        Jest.test("bool: true", (function (param) {
                var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* bools */5], "true");
                return Curry._2(Jest.Expect[/* Operators */25][/* = */5], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JBool */Block.__(2, [true]));
              }));
        Jest.test("bool: false", (function (param) {
                var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* bools */5], "false");
                return Curry._2(Jest.Expect[/* Operators */25][/* = */5], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JBool */Block.__(2, [false]));
              }));
        Jest.describe("number", (function (param) {
                Jest.test("integer", (function (param) {
                        var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* number */8], "1");
                        return Curry._2(Jest.Expect[/* Operators */25][/* = */5], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JNumber */Block.__(0, [1.0]));
                      }));
                Jest.test("float", (function (param) {
                        var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* number */8], "1.1");
                        return Curry._2(Jest.Expect[/* Operators */25][/* = */5], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JNumber */Block.__(0, [1.1]));
                      }));
                return Jest.test("signed", (function (param) {
                              var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* number */8], "-1.1");
                              return Curry._2(Jest.Expect[/* Operators */25][/* = */5], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JNumber */Block.__(0, [-1.1]));
                            }));
              }));
        Jest.describe("literal", (function (param) {
                Jest.test("null", (function (param) {
                        var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* literal */9], "null");
                        return Curry._2(Jest.Expect[/* Operators */25][/* == */0], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JNull */1);
                      }));
                Jest.test("undefined", (function (param) {
                        var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* literal */9], "undefined");
                        return Curry._2(Jest.Expect[/* Operators */25][/* == */0], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JUndefined */0);
                      }));
                Jest.test("string", (function (param) {
                        var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* literal */9], "\"what\"");
                        return Curry._2(Jest.Expect[/* Operators */25][/* = */5], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JString */Block.__(1, ["what"]));
                      }));
                Jest.test("bool: true", (function (param) {
                        var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* literal */9], "true");
                        return Curry._2(Jest.Expect[/* Operators */25][/* = */5], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JBool */Block.__(2, [true]));
                      }));
                Jest.test("bool: false", (function (param) {
                        var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* literal */9], "false");
                        return Curry._2(Jest.Expect[/* Operators */25][/* = */5], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JBool */Block.__(2, [false]));
                      }));
                return Jest.test("number", (function (param) {
                              var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* literal */9], "01.1");
                              return Curry._2(Jest.Expect[/* Operators */25][/* = */5], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JNumber */Block.__(0, [1.1]));
                            }));
              }));
        Jest.describe("array", (function (param) {
                Jest.test("empty array", (function (param) {
                        var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* array */16], "[]");
                        return Curry._2(Jest.Expect[/* Operators */25][/* = */5], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JArray */Block.__(3, [/* array */[]]));
                      }));
                Jest.test("one member", (function (param) {
                        var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* array */16], "[\"hello\"]");
                        return Curry._2(Jest.Expect[/* Operators */25][/* = */5], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JArray */Block.__(3, [/* array */[/* JString */Block.__(1, ["hello"])]]));
                      }));
                Jest.test("more members", (function (param) {
                        var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* array */16], "[\"hello\",true]");
                        return Curry._2(Jest.Expect[/* Operators */25][/* = */5], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JArray */Block.__(3, [/* array */[
                                        /* JString */Block.__(1, ["hello"]),
                                        /* JBool */Block.__(2, [true])
                                      ]]));
                      }));
                return Jest.test("space between", (function (param) {
                              var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* array */16], "[    \"hello\"   ,    true   ]");
                              return Curry._2(Jest.Expect[/* Operators */25][/* = */5], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JArray */Block.__(3, [/* array */[
                                              /* JString */Block.__(1, ["hello"]),
                                              /* JBool */Block.__(2, [true])
                                            ]]));
                            }));
              }));
        return Jest.describe("object", (function (param) {
                      Jest.test("empty object", (function (param) {
                              var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* obj */15], "{}");
                              return Curry._2(Jest.Expect[/* Operators */25][/* = */5], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JObject */Block.__(4, [/* array */[]]));
                            }));
                      Jest.test("member expression", (function (param) {
                              var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* objectMember */14], "\"hello\" : \"world\"");
                              return Curry._2(Jest.Expect[/* Operators */25][/* = */5], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* tuple */[
                                          "hello",
                                          /* JString */Block.__(1, ["world"])
                                        ]);
                            }));
                      Jest.test("one member object", (function (param) {
                              var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* obj */15], "{ \"hello\" : \"world\" }");
                              return Curry._2(Jest.Expect[/* Operators */25][/* = */5], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JObject */Block.__(4, [/* array */[/* tuple */[
                                                "hello",
                                                /* JString */Block.__(1, ["world"])
                                              ]]]));
                            }));
                      Jest.test("one member object 2", (function (param) {
                              var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* obj */15], "{ \"one\": 1 }");
                              return Curry._2(Jest.Expect[/* Operators */25][/* = */5], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JObject */Block.__(4, [/* array */[/* tuple */[
                                                "one",
                                                /* JNumber */Block.__(0, [1.0])
                                              ]]]));
                            }));
                      Jest.test("two member object", (function (param) {
                              var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* obj */15], "{ \"hello\" : \"world\", \"one\": 1 }");
                              return Curry._2(Jest.Expect[/* Operators */25][/* = */5], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JObject */Block.__(4, [/* array */[
                                              /* tuple */[
                                                "hello",
                                                /* JString */Block.__(1, ["world"])
                                              ],
                                              /* tuple */[
                                                "one",
                                                /* JNumber */Block.__(0, [1.0])
                                              ]
                                            ]]));
                            }));
                      Jest.test("two member withObject", (function (param) {
                              var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* obj */15], "{ \"hello\" : \"world\", \"one\": 1 }");
                              return Curry._2(Jest.Expect[/* Operators */25][/* = */5], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JObject */Block.__(4, [/* array */[
                                              /* tuple */[
                                                "hello",
                                                /* JString */Block.__(1, ["world"])
                                              ],
                                              /* tuple */[
                                                "one",
                                                /* JNumber */Block.__(0, [1.0])
                                              ]
                                            ]]));
                            }));
                      Jest.test("multiple keys", (function (param) {
                              var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* obj */15], "{\n                \"Company name\" : \"Microsoft Corporation\",\n                \"Ticker\"  : \"MSFT\",\n                \"Active\"  : true,\n                \"Price\"   : 30.66,\n                \"Shares outstanding\" : 8\n            }");
                              return Curry._2(Jest.Expect[/* Operators */25][/* = */5], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JObject */Block.__(4, [/* array */[
                                              /* tuple */[
                                                "Company name",
                                                /* JString */Block.__(1, ["Microsoft Corporation"])
                                              ],
                                              /* tuple */[
                                                "Ticker",
                                                /* JString */Block.__(1, ["MSFT"])
                                              ],
                                              /* tuple */[
                                                "Active",
                                                /* JBool */Block.__(2, [true])
                                              ],
                                              /* tuple */[
                                                "Price",
                                                /* JNumber */Block.__(0, [30.66])
                                              ],
                                              /* tuple */[
                                                "Shares outstanding",
                                                /* JNumber */Block.__(0, [8.0])
                                              ]
                                            ]]));
                            }));
                      Jest.test("nexted array", (function (param) {
                              var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* obj */15], "{\n                \"obj\": [1, 2]\n            }");
                              return Curry._2(Jest.Expect[/* Operators */25][/* = */5], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JObject */Block.__(4, [/* array */[/* tuple */[
                                                "obj",
                                                /* JArray */Block.__(3, [/* array */[
                                                      /* JNumber */Block.__(0, [1.0]),
                                                      /* JNumber */Block.__(0, [2.0])
                                                    ]])
                                              ]]]));
                            }));
                      Jest.test("nested empty object", (function (param) {
                              var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* obj */15], "{\n                \"obj\": {}\n            }");
                              return Curry._2(Jest.Expect[/* Operators */25][/* = */5], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JObject */Block.__(4, [/* array */[/* tuple */[
                                                "obj",
                                                /* JObject */Block.__(4, [/* array */[]])
                                              ]]]));
                            }));
                      return Jest.test("nested empty object with data", (function (param) {
                                    var result = Combinators$ReasonSuperTinyCompiler.run(JSON$ReasonSuperTinyCompiler.Parser[/* obj */15], "{\n                \"obj\": {\n                    \"hello\": \"world\"\n                }\n            }");
                                    return Curry._2(Jest.Expect[/* Operators */25][/* = */5], Jest.Expect[/* expect */0](Combinators$ReasonSuperTinyCompiler.get_exn(result)), /* JObject */Block.__(4, [/* array */[/* tuple */[
                                                      "obj",
                                                      /* JObject */Block.__(4, [/* array */[/* tuple */[
                                                              "hello",
                                                              /* JString */Block.__(1, ["world"])
                                                            ]]])
                                                    ]]]));
                                  }));
                    }));
      }));

/*  Not a pure module */
