// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE

import * as Block from "../node_modules/bs-platform/lib/es6/block.js";
import * as Scheme$BsParse from "./Scheme.bs.js";
import * as Caml_js_exceptions from "../node_modules/bs-platform/lib/es6/caml_js_exceptions.js";
import * as Scheme_Interpreter$BsParse from "./Scheme_Interpreter.bs.js";

var code = "(if #t (+ 1 2) (- 3 2))";

var result;

try {
  result = Scheme$BsParse.$$eval(code);
}
catch (raw_exn){
  var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
  if (exn[0] === Scheme_Interpreter$BsParse.RuntimeError) {
    result = /* String */Block.__(2, [exn[1]]);
  } else {
    throw exn;
  }
}

console.log("The result is: " + Scheme$BsParse.show(result));

export {
  code ,
  result ,
  
}
/* result Not a pure module */
