// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE

import * as List from "../node_modules/bs-platform/lib/es6/list.js";
import * as $$String from "../node_modules/bs-platform/lib/es6/string.js";
import * as Util$BsParse from "./Util.bs.js";

function make(input, offset) {
  return /* record */[
          /* input */input,
          /* offset */offset
        ];
}

function line(loc) {
  var countBreaks = function (str) {
    return List.fold_left((function (acc, v) {
                  if (v === /* "\n" */10) {
                    return acc + 1 | 0;
                  } else {
                    return acc;
                  }
                }), 0, Util$BsParse.explode(str));
  };
  return countBreaks($$String.sub(loc[/* input */0], 0, loc[/* offset */1] + 1 | 0)) + 1 | 0;
}

function col(loc) {
  var lines = $$String.sub(loc[/* input */0], 0, loc[/* offset */1] + 1 | 0).split("\n").reverse();
  return lines[0].length;
}

function inc(loc, offset) {
  return /* record */[
          /* input */loc[/* input */0],
          /* offset */loc[/* offset */1] + offset | 0
        ];
}

export {
  make ,
  line ,
  col ,
  inc ,
  
}
/* No side effect */
