// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$String = require("bs-platform/lib/js/string.js");
var Util$ReasonSuperTinyCompiler = require("./Util.bs.js");

function make(input, offset) {
  return /* record */[
          /* input */input,
          /* offset */offset
        ];
}

function line(loc) {
  var countBreaks = function (str) {
    return List.fold_left((function (acc, v) {
                  if (v === /* "\n" */10) {
                    return acc + 1 | 0;
                  } else {
                    return acc;
                  }
                }), 0, Util$ReasonSuperTinyCompiler.explode(str));
  };
  return countBreaks($$String.sub(loc[/* input */0], 0, loc[/* offset */1] + 1 | 0)) + 1 | 0;
}

function col(loc) {
  var lines = $$String.sub(loc[/* input */0], 0, loc[/* offset */1] + 1 | 0).split("\n").reverse();
  return lines[0].length;
}

function inc(loc, offset) {
  return /* record */[
          /* input */loc[/* input */0],
          /* offset */loc[/* offset */1] + offset | 0
        ];
}

exports.make = make;
exports.line = line;
exports.col = col;
exports.inc = inc;
/* No side effect */
