// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE

import * as $$Array from "../node_modules/bs-platform/lib/es6/array.js";
import * as Location$ReasonSuperTinyCompiler from "./Location.bs.js";

function makeWith(stack, failures) {
  return /* record */[
          /* stack */stack,
          /* otherFailures */failures
        ];
}

function make(loc, string) {
  return /* record */[
          /* stack : array */[/* tuple */[
              loc,
              string
            ]],
          /* otherFailures : array */[]
        ];
}

function getStackTrace(error) {
  return $$Array.fold_left((function (acc, param) {
                var loc = param[0];
                var line = Location$ReasonSuperTinyCompiler.line(loc);
                var column = Location$ReasonSuperTinyCompiler.col(loc);
                var finalMessage = "" + (String(param[1]) + (" at line " + (String(line) + (", column " + (String(column) + "")))));
                return acc.concat(/* array */[finalMessage]);
              }), /* array */[], error[/* stack */0]);
}

function getAllStackTrace(error) {
  var otherFailureStackTraces = $$Array.fold_left($$Array.append, /* array */[], $$Array.map(getStackTrace, error[/* otherFailures */1]));
  return $$Array.append(getStackTrace(error), otherFailureStackTraces);
}

function toString(error) {
  return getAllStackTrace(error).join("\n");
}

export {
  makeWith ,
  make ,
  getStackTrace ,
  getAllStackTrace ,
  toString ,
  
}
/* No side effect */
