// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE

import * as Util$ReasonSuperTinyCompiler from "./Util.bs.js";
import * as Combinators$ReasonSuperTinyCompiler from "./Combinators.bs.js";
import * as Scheme_Parser$ReasonSuperTinyCompiler from "./Scheme_Parser.bs.js";
import * as Scheme_Interpreter$ReasonSuperTinyCompiler from "./Scheme_Interpreter.bs.js";

function parse(param) {
  return Combinators$ReasonSuperTinyCompiler.run(Scheme_Parser$ReasonSuperTinyCompiler.expr, param);
}

function $$eval(param) {
  return Util$ReasonSuperTinyCompiler.$less$less((function (param) {
                return Util$ReasonSuperTinyCompiler.$less$less(Scheme_Interpreter$ReasonSuperTinyCompiler.$$eval, Combinators$ReasonSuperTinyCompiler.get_exn, param);
              }), parse, param);
}

var Parser = 0;

var Interpreter = 0;

var show = Scheme_Interpreter$ReasonSuperTinyCompiler.showVal;

export {
  Parser ,
  Interpreter ,
  parse ,
  $$eval ,
  show ,
  
}
/* Combinators-ReasonSuperTinyCompiler Not a pure module */
