// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Combinators$ReasonSuperTinyCompiler = require("./Combinators.bs.js");
var Scheme_Parser$ReasonSuperTinyCompiler = require("./Scheme_Parser.bs.js");
var Scheme_Interpreter$ReasonSuperTinyCompiler = require("./Scheme_Interpreter.bs.js");

function $$eval(code) {
  return Scheme_Interpreter$ReasonSuperTinyCompiler.$$eval(Combinators$ReasonSuperTinyCompiler.get_exn(Combinators$ReasonSuperTinyCompiler.run(Scheme_Parser$ReasonSuperTinyCompiler.expr, code)));
}

var Parser = 0;

var Interpreter = 0;

var show = Scheme_Interpreter$ReasonSuperTinyCompiler.showVal;

exports.Parser = Parser;
exports.Interpreter = Interpreter;
exports.$$eval = $$eval;
exports.show = show;
/* Combinators-ReasonSuperTinyCompiler Not a pure module */
